"use client";
import type { ComponentProps } from "react";
import type ShopLanding from "../../book/[shopslug]/shop-landing";
import { formatCurrency } from "@/lib/utils";
export default function LuxuryLanding({ shop, services, barbers, reviews = [], canGiftCard, onBookNow }: ComponentProps<typeof ShopLanding>) {
  const words=shop.name.trim().split(/\s+/);const split=Math.max(1,Math.floor(words.length/2));
  const location=[shop.address,shop.city,shop.province,shop.postal_code].filter(Boolean).join(", ");
  return <div className="lux-template">
    <a className="skip" href="#main">Skip to content</a>
    <header className="topbar"><div className="wrap"><a className="brand" href="#main">{shop.name.toUpperCase()}<span>BARBER STUDIO</span></a><nav className="links" aria-label="Main navigation"><a href="#services">The services</a><a href="#work">The craft</a><a href="#visit">Visit us</a><button className="solid" onClick={onBookNow}>Book now</button></nav></div></header>
    <main id="main" className="wrap">
      <section className="hero" aria-labelledby="shop-name"><div className="hero-top"><span className="eyebrow">Barber studio{shop.city ? ` / ${shop.city}` : ""}</span><span className="concept">Design preview</span></div><h1 id="shop-name"><span>{words.slice(0,split).join(" ").toUpperCase()}</span>{words.length>1&&<span className="second">{words.slice(split).join(" ").toUpperCase()}</span>}</h1><div className="hero-bottom"><p>{shop.description || <>Good cuts. Quiet confidence.<br/>A little time, just for you.</>}</p><a href="#services" className="text-link">Find your service <span aria-hidden="true">↓</span></a></div><figure className="hero-photo"><img src="/shopfront-reference/hero-shop.jpg" alt="Reference photography: a barber at work in a brick-lined studio" width="2000" height="1335" fetchPriority="high"/><figcaption className="photo-caption"><span>THE STUDIO / A PLACE TO RESET</span><span>Reference photography</span></figcaption></figure></section>
      <section className="section" id="services"><div className="section-head"><div><span className="eyebrow">01 / In the chair</span><h2>The essentials,<br/>done with care.</h2></div><p className="muted">Shop service menu<br/>Prices shown in CAD</p></div><div className="services"><p className="intro">From a fresh shape to a close finish. Choose a service, take a seat, and make the next hour yours.</p><div>{services.map(s=><button className="service" key={s.id} onClick={onBookNow}><span><strong>{s.name}</strong><small>{s.description ? `${s.description} · ` : ""}{s.duration_minutes} min</small></span><span className="price">{formatCurrency(s.price)}</span><span className="arrow" aria-hidden="true">↗</span></button>)}{services.length===0&&<p>Services will appear here when the shop makes them available.</p>}</div></div></section>
      <section className="section" id="work"><div className="section-head"><div><span className="eyebrow">02 / The craft</span><h2>It’s in the details.</h2></div><p className="muted">Reference images.<br/>Your portfolio goes here.</p></div><div className="gallery"><figure><img src="/shopfront-reference/atmo-fade.jpg" alt="Reference: detailed haircut with a comb and scissors" loading="lazy" width="1000" height="1500"/><figcaption><span>Shape &amp; texture</span><span>01</span></figcaption></figure><figure><img src="/shopfront-reference/atmo-tools.jpg" alt="Reference: professional barber tools" loading="lazy" width="1500" height="1000"/><figcaption><span>Tools of the trade</span><span>02</span></figcaption></figure></div></section>
      <section className="section"><div className="section-head"><div><span className="eyebrow">03 / Your people</span><h2>Find your chair.</h2></div></div><div className="team">{barbers.map(b=><article key={b.id}>{b.photo?<img className="profile-photo" src={b.photo} alt={b.name} width="58" height="66" loading="lazy"/>:<div className="monogram" aria-hidden="true">{b.name.split(/\s+/).slice(0,2).map(n=>n[0]).join("")}</div>}<div><h3>{b.name}</h3>{b.bio&&<p>{b.bio}</p>}{!b.photo&&<p>Photo coming soon</p>}{b.total_reviews>0&&<p>{b.rating.toFixed(1)} / 5 · {b.total_reviews} reviews</p>}</div></article>)}</div></section>
      {reviews.length>0&&<section className="section client-reviews" aria-label="Client reviews">{reviews.slice(0,3).map((r,i)=><blockquote key={i}><p>“{r.comment}”</p><footer>{r.name} · {r.rating}/5</footer></blockquote>)}</section>}
      <section className="section visit" id="visit"><div><span className="eyebrow">04 / Come on in</span><h2>Your next<br/>good hair day.</h2><address>{location}{shop.phone&&<><br/><a href={`tel:${shop.phone}`}>{shop.phone}</a></>}</address></div><div><ul className="hours" aria-label="Sample opening hours"><li>Monday – Friday<span>09:00 – 18:00</span></li><li>Saturday<span>09:00 – 16:00</span></li><li>Sunday<span>Closed</span></li></ul><p className="note">Sample hours for this design preview. Use the booking calendar for actual availability.</p><button className="solid" onClick={onBookNow}>Find a time</button></div></section>
      {canGiftCard&&<p className="gift-link"><a href={`/gift/${shop.slug}`}>Give a gift card ↗</a></p>}
      <footer className="footer"><span>{shop.name.toUpperCase()} · Shopfront preview</span><span>Built around your shop. Powered by ClipWise.</span><span>Reference photos · real booking flow</span></footer>
    </main><div className="mobile-book"><p><strong>Your chair is waiting.</strong>Find your next appointment</p><button className="solid" onClick={onBookNow}>Book now</button></div>
  </div>;
}
